development:
  encoding: unicode
  adapter: postgresql
  pool: 5
  database: 'postgres'
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432
test:
  encoding: unicode
  adapter: postgresql
  pool: 5
  database: 'postgres'
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432
production:
  encoding: unicode
  adapter: postgresql
  pool: 5
  database: 'postgres'
  username: 'postgres'
  password: 'postgres'
  host: 'localhost'
  port: 5432 